function i=response_info(t,o)
    i=struct('status','unresolved','converged',false,'certified',false, ...
        'method',o.Method,'abscissa',NaN,'singularityBound',[], ...
        'domainSource','','assumptions',{{}},'warnings',{{}}, ...
        'time',t,'internalStep',NaN,'fftPeriod',NaN,'bandwidth',NaN, ...
        'points',0,'evaluations',0,'amplification',1,'symmetryError',0, ...
        'errorEstimate',inf(size(t)),'resolvedMask',false(size(t)), ...
        'periodError',inf(size(t)),'bandwidthError',inf(size(t)), ...
        'shiftError',inf(size(t)),'history',[], 'stopReason','not evaluated', ...
        'singularTerms',struct('time',{},'order',{},'weight',{}), ...
        'interpolation','','inputErrorEstimate',NaN, ...
        'endpointPolicy','Analytical right limits only; unknown zero-time values are unresolved.');
end
