function study = run_pade_pitfalls(rootDir)
%RUN_PADE_PITFALLS Experiments showing what diagonal Pade keeps and loses.
%   1. Universal phase of exp(-iy) versus [n/n] Pade and its validity range.
%   2. Step response of a pure delay versus its Pade realizations.
%   3. Time simulation of P1 at T=1.5: exact DDE versus Pade models.
%   4. Number of unstable roots Z(T) of P3: exact (crossings + bound-based
%      argument-principle count) versus Pade polynomial roots.
    % Resolve paths from this file, so the study runs from any folder.
    here=fileparts(mfilename('fullpath')); repo=fileparts(fileparts(here));
    if exist('croots','file')~=2, run(fullfile(repo,'setup_contourroots.m')); end
    if nargin<1, rootDir=fullfile(repo,'output','time_delay'); end
    figDir=fullfile(rootDir,'figures');
    dataDir=fullfile(rootDir,'data');
    if ~exist(figDir,'dir'), mkdir(figDir); end
    if ~exist(dataDir,'dir'), mkdir(dataDir); end
    set(groot,'defaultAxesFontSize',16,'defaultAxesFontName','Helvetica', ...
        'defaultLineLineWidth',1.6,'defaultFigureColor','w');
    col=[0.04 0.25 0.52; 0.86 0.24 0.18; 0.96 0.58 0.12; 0.10 0.58 0.48; ...
         0.48 0.16 0.62; 0.35 0.35 0.35];

    %% 1. Universal phase and range of validity
    orders=[1 2 4 8 12];
    y=linspace(0,40,8001);
    f=figure('Position',[80 80 1100 430]);
    tl=tiledlayout(f,1,2,'TileSpacing','compact','Padding','compact');
    ax1=nexttile(tl); hold(ax1,'on');
    plot(ax1,y,-y,'k-','LineWidth',2.4,'DisplayName','exata: -y');
    ax2=nexttile(tl); hold(ax2,'on');
    for j=1:numel(orders)
        ph=pade_phase(orders(j),y);
        plot(ax1,y,ph,'Color',col(j+1,:),'DisplayName',sprintf('[%d/%d]',orders(j),orders(j)));
        err=abs(ph+y); err(err<1e-16)=1e-16;
        semilogy(ax2,y,err,'Color',col(j+1,:),'DisplayName',sprintf('[%d/%d]',orders(j),orders(j)));
    end
    for j=1:numel(orders)
        yline(ax1,-orders(j)*pi,':','Color',[.6 .6 .6],'HandleVisibility','off');
    end
    xlabel(ax1,'y = \omega T'); ylabel(ax1,'unwrapped phase [rad]');
    title(ax1,'(a) Phase of e^{-iy} and of Padé'); ylim(ax1,[-40 1]);
    legend(ax1,'Location','southwest'); grid(ax1,'on'); box(ax1,'on');
    set(ax2,'YScale','log'); ylim(ax2,[1e-14 10]); grid(ax2,'on'); box(ax2,'on');
    yline(ax2,1e-2,'--','Color',[.3 .3 .3],'HandleVisibility','off');
    xlabel(ax2,'y = \omega T'); ylabel(ax2,'|phase error| [rad]');
    title(ax2,'(b) Phase error'); legend(ax2,'Location','southeast');
    save_figure(f,figDir,'pade_phase_universal');

    allOrders=1:12; tols=[1e-1 1e-2 1e-6];
    yValid=NaN(numel(allOrders),numel(tols));
    yy=linspace(0,60,120001);
    for i=1:numel(allOrders)
        err=abs(pade_phase(allOrders(i),yy)+yy);
        for k=1:numel(tols)
            yValid(i,k)=yy(find(err>tols(k),1)-1);
        end
    end
    fid=fopen(fullfile(dataDir,'pade_validity_table.tex'),'w');
    fprintf(fid,'%% Generated by run_pade_pitfalls.m\n');
    fprintf(fid,'\\begin{tabular}{rrrrr}\\toprule\n');
    fprintf(fid,'%s\n','$n$ & $y_{0.1}$ & $y_{0.01}$ & $y_{10^{-6}}$ & limit phase $-n\pi$ \\ \midrule');
    for i=[1 2 3 4 6 8 10 12]
        fprintf(fid,'%d & %.3f & %.3f & %.3f & %.2f %s\n',allOrders(i),yValid(i,:),-allOrders(i)*pi,'\\');
    end
    fprintf(fid,'\\bottomrule\\end{tabular}\n'); fclose(fid);

    %% 2. Step response of a pure delay
    f=figure('Position',[80 80 1000 400]); ax=axes(f); hold(ax,'on');
    t=linspace(0,3,3001);
    stairs(ax,[0 1 3],[0 1 1],'k-','LineWidth',2.4,'DisplayName','e^{-s} (exact)');
    shown=[1 2 4 8];
    for j=1:numel(shown)
        [pn,qn]=pade_delay(1,shown(j));
        yStep=step(tf(pn,qn),t);
        plot(ax,t,yStep,'Color',col(j+1,:),'DisplayName',sprintf('[%d/%d]',shown(j),shown(j)));
    end
    grid(ax,'on'); box(ax,'on'); ylim(ax,[-1.15 1.35]);
    xlabel(ax,'time t / T'); ylabel(ax,'step response');
    title(ax,'Pure delay and its diagonal Padé approximations (T = 1)');
    legend(ax,'Location','southeast');
    save_figure(f,figDir,'pade_step_response');

    %% 3. Time simulation of P1: x'(t) = -x(t) - 2 x(t-T), history x=1
    T=1.5; tEnd=40;
    sol=dde23(@(t,x,z) -x-2*z,T,1,[0 tEnd],ddeset('RelTol',1e-8,'AbsTol',1e-10));
    f=figure('Position',[80 80 1000 420]); ax=axes(f); hold(ax,'on');
    plot(ax,sol.x,sol.y,'k-','LineWidth',2.2,'DisplayName','exact (dde23)');
    simOrders=[1 2 4];
    simData=struct('order',{},'t',{},'x',{},'alpha',{});
    for j=1:numel(simOrders)
        n=simOrders(j);
        [pn,qn]=pade_delay(T,n);
        [A,B,C,Dd]=tf2ss(pn,qn);
        % closed loop: x' = -x - 2 w, w = C xf + Dd x, xf' = A xf + B x
        Acl=[-1-2*Dd, -2*C; B, A];
        xf0=-A\B;                          % filter at rest with constant input 1
        [tt,xx]=ode45(@(t,z) Acl*z,[0 tEnd],[1; xf0],odeset('RelTol',1e-9,'AbsTol',1e-11));
        simData(j)=struct('order',n,'t',tt,'x',xx(:,1),'alpha',max(real(eig(Acl))));
        plot(ax,tt,xx(:,1),'Color',col(j+1,:),'DisplayName',sprintf('Padé [%d/%d]',n,n));
    end
    grid(ax,'on'); box(ax,'on'); ylim(ax,[-6 6]);
    xlabel(ax,'time t'); ylabel(ax,'x(t)');
    title(ax,'P1 with T = 1.5: x''(t) = -x(t) - 2x(t-T), history x \equiv 1');
    legend(ax,'Location','southwest');
    save_figure(f,figDir,'p1_time_simulation');

    %% 4. Unstable-root count for P3
    N=3; D=[1 .8 4]; Tmax=10;
    exact=critical_delays(N,D,Tmax);
    padeOrders=[1 2 3 4 5 6 8 10 12];
    predicted=pade_critical_delays(N,D,Tmax,padeOrders);
    % Crossing direction depends only on sign G'(omega) (Appendix A), and
    % the same holds for diagonal Pade; take it from the exact table.
    dirOf=@(w) sign(exact.CrossingSpeed(find(abs(exact.Frequency-w)<1e-7,1)));
    Tgrid=linspace(0.005,Tmax,4000);
    Zexact=staircase(exact.Delay,sign(exact.CrossingSpeed),Tgrid);
    % bound-based argument-principle check away from critical delays
    Tcheck=linspace(0.05,Tmax-0.05,80);
    Tcheck=Tcheck(min(abs(Tcheck(:)-exact.Delay.'),[],2)>0.02);
    Zcheck=arrayfun(@(tt) unstable_root_count(N,D,tt,6000),Tcheck);
    assert(all(Zcheck==staircase(exact.Delay,sign(exact.CrossingSpeed),Tcheck)), ...
        'Argument principle disagrees with crossing count.');
    Zpade=zeros(numel(padeOrders),numel(Tgrid));
    for i=1:numel(padeOrders)
        rows=predicted(predicted.Order==padeOrders(i),:);
        dirs=arrayfun(dirOf,rows.Frequency);
        Zpade(i,:)=staircase(rows.Delay,dirs,Tgrid);
        % independent check: roots of the Pade polynomial
        Tsub=Tgrid(1:40:end);
        Tsub=Tsub(min(abs(Tsub(:)-rows.Delay.'),[],2)>0.02);
        Zpoly=arrayfun(@(tt) pade_unstable_count(N,D,tt,padeOrders(i)),Tsub);
        assert(all(Zpoly==staircase(rows.Delay,dirs,Tsub)), ...
            'Pade polynomial count disagrees for order %d.',padeOrders(i));
    end

    % Numerical fragility: raw polynomial roots versus balanced state space
    Tfrag=linspace(0.02,1,99); fragOrders=[4 6 8 10 12];
    fragility=zeros(size(fragOrders));
    for i=1:numel(fragOrders)
        for tt=Tfrag
            zr=sum(real(roots(pade_characteristic(N,D,tt,fragOrders(i))))>0);
            fragility(i)=fragility(i)+(zr~=pade_unstable_count(N,D,tt,fragOrders(i)));
        end
    end
    fprintf('Spurious RHP counts from polynomial roots (of %d delays):',numel(Tfrag));
    fprintf(' n=%d:%d',[fragOrders;fragility]); fprintf('\n');

    shownZ=[2 4 5 8];
    f=figure('Position',[80 80 1000 760]);
    tl=tiledlayout(f,numel(shownZ),1,'TileSpacing','tight','Padding','compact');
    for j=1:numel(shownZ)
        ax=nexttile(tl); hold(ax,'on');
        i=find(padeOrders==shownZ(j));
        wrong=(Zexact==0)~=(Zpade(i,:)==0);
        shade_regions(ax,Tgrid,wrong,[0 7]);
        stairs(ax,Tgrid,Zexact,'k-','LineWidth',2.4,'DisplayName','exact');
        stairs(ax,Tgrid,Zpade(i,:),'-','Color',col(2,:),'LineWidth',1.8, ...
            'DisplayName',sprintf('Padé [%d/%d]',shownZ(j),shownZ(j)));
        plot(ax,Tcheck,Zcheck,'o','MarkerSize',4,'Color',[.3 .3 .3], ...
            'HandleVisibility','off');
        ylim(ax,[-0.4 7]); yticks(ax,0:2:6); xlim(ax,[0 Tmax]);
        grid(ax,'on'); box(ax,'on'); ylabel(ax,'Z(T)');
        legend(ax,'Location','northwest','Orientation','horizontal');
        if j<numel(shownZ), ax.XTickLabel=[]; end
    end
    xlabel(ax,'delay T');
    title(tl,'P3: number of right-half-plane roots (shaded: wrong stability conclusion)');
    save_figure(f,figDir,'p3_unstable_count');

    % Stability intervals table
    fid=fopen(fullfile(dataDir,'p3_stability_intervals.tex'),'w');
    fprintf(fid,'%% Generated by run_pade_pitfalls.m\n');
    fprintf(fid,'\\begin{tabular}{lll}\\toprule\n');
    fprintf(fid,'%s\n','Model & stable intervals in $[0,10]$ & $Z(10)$ \\ \midrule');
    fprintf(fid,'exact & %s & %d %s\n',intervals_text(exact.Delay,sign(exact.CrossingSpeed),Tmax), ...
        Zexact(end),'\\');
    for i=1:numel(padeOrders)
        rows=predicted(predicted.Order==padeOrders(i),:);
        dirs=arrayfun(dirOf,rows.Frequency);
        fprintf(fid,'Padé [%d/%d] & %s & %d %s\n',padeOrders(i),padeOrders(i), ...
            intervals_text(rows.Delay,dirs,Tmax),Zpade(i,end),'\\');
    end
    fprintf(fid,'\\bottomrule\\end{tabular}\n'); fclose(fid);

    study=struct('yValid',yValid,'tols',tols,'simulation',simData, ...
        'p3exact',exact,'p3pade',predicted,'Tgrid',Tgrid,'Zexact',Zexact, ...
        'Zpade',Zpade,'padeOrders',padeOrders,'Tcheck',Tcheck,'Zcheck',Zcheck, ...
        'p1bound',rhp_root_bound(2,[1 1]),'p3bound',rhp_root_bound(N,D), ...
        'fragilityOrders',fragOrders,'fragility',fragility,'fragilityDelays',Tfrag);
    save(fullfile(dataDir,'pade_pitfalls.mat'),'study');
    fprintf('P1 bound R=%.4f, P3 bound R=%.4f\n',study.p1bound,study.p3bound);
    for j=1:numel(simData)
        fprintf('Pade %d/%d closed-loop abscissa at T=1.5: %+.5f\n',simData(j).order,simData(j).order,simData(j).alpha);
    end
    disp(yValid);
end

function ph=pade_phase(n,y)
    [pn,qn]=pade_delay(1,n);
    ph=unwrap(angle(polyval(pn,1i*y)./polyval(qn,1i*y)));
end

function Z=pade_unstable_count(N,D,T,n)
    % Balanced state-space realization is far better conditioned than the
    % expanded characteristic polynomial for high orders and small delays.
    [pn,qn]=pade_delay(T,n);
    sys=feedback(ss(tf(N,D))*ss(tf(pn,qn)),1);
    Z=sum(real(eig(sys.A))>0);
end

function Z=staircase(Tc,dirs,T)
    Z=zeros(size(T));
    for k=1:numel(Tc), Z=Z+2*dirs(k)*(T>Tc(k)); end
end

function txt=intervals_text(Tc,dirs,Tmax)
    [Tc,idx]=sort(Tc); dirs=dirs(idx);
    Z=0; start=0; parts={};
    for k=1:numel(Tc)
        newZ=Z+2*dirs(k);
        if Z==0 && newZ>0, parts{end+1}=sprintf('$[%s,\\,%.4f)$',fmt(start),Tc(k)); end %#ok<AGROW>
        if Z>0 && newZ==0, start=Tc(k); end
        Z=newZ;
    end
    if Z==0, parts{end+1}=sprintf('$(%.4f,\\,%d]$',start,Tmax); end
    txt=strjoin(parts,', ');
end

function s=fmt(x)
    if x==0, s='0'; else, s=sprintf('%.4f',x); end
end

function shade_regions(ax,T,mask,yl)
    d=diff([0 mask(:).' 0]); a=find(d==1); b=find(d==-1)-1;
    for k=1:numel(a)
        patch(ax,[T(a(k)) T(b(k)) T(b(k)) T(a(k))],[yl(1) yl(1) yl(2) yl(2)], ...
            [0.99 0.80 0.78],'EdgeColor','none','FaceAlpha',0.8,'HandleVisibility','off');
    end
end

function save_figure(fig,figDir,name)
    exportgraphics(fig,fullfile(figDir,[name '.pdf']),'ContentType','vector');
    exportgraphics(fig,fullfile(figDir,[name '.png']),'Resolution',200);
end
